package com.interview.altimetrik.banktransfer;

import jakarta.annotation.PostConstruct;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.math.BigDecimal;
import java.util.Map;

/**
 * ============================================================
 * LAYER 7 — Controller (@RestController)
 * ============================================================
 *
 * PURPOSE:
 *   HTTP entry point. Maps URLs to methods, validates input, returns JSON.
 *   THIN layer — no business logic. Just: receive → validate → delegate → respond.
 *
 * ---- @RestController vs @Controller ----
 *   @Controller           → returns a view name (Thymeleaf / JSP template)
 *   @RestController       → returns JSON/XML directly (= @Controller + @ResponseBody)
 *   For REST APIs always use @RestController.
 *
 * ---- @RequestMapping("/api/bank") ----
 *   Sets base URL for all endpoints in this class.
 *   Endpoint URLs are: base + method-level mapping.
 *     POST /api/bank/transfer
 *     GET  /api/bank/accounts/{id}
 *
 * ---- @Valid ON @RequestBody ----
 *   Triggers Bean Validation on the incoming DTO BEFORE the method body runs.
 *   If any @NotNull / @DecimalMin fails → Spring returns 400 automatically.
 *   Without @Valid: validation annotations on the DTO are silently ignored.
 *   Without @RequestBody: Spring won't parse the JSON body.
 *
 * ---- @ExceptionHandler (INTERVIEW MUST-KNOW) ----
 *   Catches specific exceptions thrown anywhere in this controller.
 *   Maps them to HTTP responses without try-catch in every method.
 *
 *   @ExceptionHandler vs @ControllerAdvice:
 *     @ExceptionHandler in a controller  → only catches from THIS controller
 *     @ControllerAdvice (separate class) → catches from ALL controllers globally
 *   For a single controller, inline @ExceptionHandler is fine and simpler.
 *   For production apps with many controllers, use @ControllerAdvice.
 *
 * ---- ResponseEntity<T> ----
 *   Gives full control over the HTTP response: status code + headers + body.
 *     ResponseEntity.ok(body)                → 200 OK with body
 *     ResponseEntity.badRequest().body(body) → 400 Bad Request with body
 *     ResponseEntity.notFound().build()      → 404 No body
 *   Without ResponseEntity: Spring defaults to 200 OK for any return value.
 *
 * ---- @PostConstruct DATA INITIALIZATION ----
 *   Runs ONCE after Spring creates this bean (after constructor + DI).
 *   Used here to preload two accounts into H2 so the app works immediately.
 *   Alternative approaches: data.sql in resources, CommandLineRunner @Bean, @EventListener.
 * ============================================================
 */
@RestController
@RequestMapping("/api/bank")
@RequiredArgsConstructor
public class AccountController {

    private final AccountService accountService;
    private final BankAccountRepository repo;
    // Both injected via constructor (generated by @RequiredArgsConstructor)

    // ============================================================
    // DATA INITIALIZATION — runs once at startup
    // Creates 2 sample accounts if none exist
    // ============================================================
    @PostConstruct
    public void init() {
        if (repo.count() == 0) {
            repo.save(BankAccount.builder()
                .accountNumber("ACC001")
                .ownerName("Alice")
                .balance(new BigDecimal("100000.00"))
                .build());

            repo.save(BankAccount.builder()
                .accountNumber("ACC002")
                .ownerName("Bob")
                .balance(new BigDecimal("20000.00"))
                .build());

            System.out.println("=== Bank accounts preloaded: Alice (100000), Bob (20000) ===");
        }
    }

    // ============================================================
    // POST /api/bank/transfer
    // Transfers money from one account to another
    //
    // @Valid         → triggers Bean Validation on TransferRequest fields
    // @RequestBody   → parses JSON body into TransferRequest object
    // ResponseEntity → lets us control HTTP status code in response
    // ============================================================
    @PostMapping("/transfer")
    public ResponseEntity<TransferResponse> transfer(
            @Valid @RequestBody TransferRequest request) {

        TransferResponse response = accountService.transfer(request);
        return ResponseEntity.ok(response);
        // ResponseEntity.ok() → HTTP 200 OK with body as JSON
    }

    // ============================================================
    // GET /api/bank/accounts/{id}
    // Returns account details for the given ID
    //
    // @PathVariable → extracts {id} from the URL path
    // ============================================================
    @GetMapping("/accounts/{id}")
    public ResponseEntity<BankAccount> getAccount(@PathVariable Long id) {
        BankAccount account = accountService.findById(id);
        return ResponseEntity.ok(account);
    }

    // ============================================================
    // EXCEPTION HANDLERS
    // These intercept exceptions thrown by the methods above.
    // No try-catch needed in the endpoint methods.
    // ============================================================

    // Handles: insufficient balance → 400 Bad Request
    @ExceptionHandler(InsufficientBalanceException.class)
    public ResponseEntity<Map<String, String>> handleInsufficientBalance(
            InsufficientBalanceException ex) {

        return ResponseEntity
            .badRequest()           // 400
            .body(Map.of(           // JSON: { "error": "Account 2 has insufficient balance: 20000" }
                "error", ex.getMessage()
            ));
    }

    // Handles: account not found → 404 Not Found
    @ExceptionHandler(EntityNotFoundException.class)
    public ResponseEntity<Map<String, String>> handleNotFound(
            EntityNotFoundException ex) {

        return ResponseEntity
            .notFound()             // 404 — no body (notFound() only has .build() or .header())
            .build();
        // If you want a body with 404: ResponseEntity.status(404).body(Map.of("error", ex.getMessage()))
    }
}
